- name: Send custom Discord notification
  if: always()
  run: |
    curl -X POST -H "Content-Type: application/json" \
      -d '{
        "username": "GitHub Actions",
        "embeds": [{
          "title": "Build Status",
          "description": "The GitHub Actions workflow has completed.",
          "color": 7506394,
          "fields": [
            {
              "name": "Status",
              "value": "Success",
              "inline": true
            }
          ]
        }]
      }' \
      ${{ secrets.DISCORD_WEBHOOK_URL }}
