name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow when creating a pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send "Started" Discord notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "username": "GitHub Actions",
              "avatar_url": "https://avatars.githubusercontent.com/u/9919?s=200&v=4",
              "embeds": [
                {
                  "title": "Build Started: ${{ github.event.head_commit.message }}",  # Commit message as the title
                  "description": "The GitHub Actions workflow has started.",
                  "color": 16776960,  # Yellow color for "Started"
                  "fields": [
                    {
                      "name": "Status",
                      "value": "Started",
                      "inline": true
                    },
                    {
                      "name": "Commit",
                      "value": "${{ github.sha }}",
                      "inline": true
                    }
                  ]
                }
              ]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: npm test

      - name: Send "Finished" Discord notification
        if: always()  # This ensures the notification is sent regardless of the job status
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "username": "GitHub Actions",
              "avatar_url": "https://avatars.githubusercontent.com/u/9919?s=200&v=4",
              "embeds": [
                {
                  "title": "Build Finished: ${{ github.event.head_commit.message }}",  # Commit message as the title
                  "description": "The GitHub Actions workflow has completed.",
                  "color": ${{ job.status == 'success' && '3066993' || '15158332' }},  # Green for success, Red for failure
                  "fields": [
                    {
                      "name": "Status",
                      "value": "${{ job.status | capitalize }}",
                      "inline": true
                    },
                    {
                      "name": "Commit",
                      "value": "${{ github.sha }}",
                      "inline": true
                    },
                    {
                      "name": "Run URL",
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "inline": false
                    }
                  ]
                }
              ]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
