name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Other job steps (e.g., build, tests)
      
      - name: Send Discord notification
        if: always() # Send notification even if the job fails
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "GitHub Actions run completed!"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
